name: CI

on:
  push:

jobs:
  ci:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v4

      - name: Use Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 20

      - name: yarn install
        run: |
          yarn install --frozen-lockfile

      - name: build
        run: yarn run build

      - name: check
        run: yarn run check

      - name: lint
        if: always()
        run: yarn run lint
